# Generated by Django 5.2.13 on 2026-04-21 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='syncedarticle',
            name='article_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='syncedarticle',
            name='editorial_decision',
            field=models.CharField(choices=[('default', '기본'), ('feature', '상단 노출'), ('exclude', '배제')], default='default', max_length=16),
        ),
        migrations.AddField(
            model_name='syncedarticle',
            name='editorial_feature_rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncedarticle',
            name='editorial_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syncedarticle',
            name='editorial_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncedarticle',
            name='editorial_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorially_updated_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syncedarticle',
            name='importance_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncedarticle',
            name='is_noise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='syncedarticle',
            name='is_official_source',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='syncedarticle',
            name='selection_bucket',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='syncedarticle',
            name='source_kind',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
