# Generated by Django 5.2.13 on 2026-04-21 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefings', '0002_syncedarticle_article_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('editorial', 'Editorial'), ('contact', 'Contact'), ('publish', 'Publish'), ('role', 'Role')], max_length=32)),
                ('action', models.CharField(max_length=80)),
                ('target_key', models.CharField(blank=True, max_length=300)),
                ('summary', models.CharField(max_length=300)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['scope', 'created_at'], name='audit_scope_created_idx'), models.Index(fields=['created_at'], name='audit_created_idx')],
            },
        ),
    ]
