# Generated by Django 5.2.13 on 2026-04-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefings', '0003_adminauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_scope', models.CharField(choices=[('public', 'Public'), ('institution', 'Institution')], default='public', max_length=20)),
                ('visitor_id', models.CharField(max_length=80)),
                ('session_id', models.CharField(blank=True, max_length=80)),
                ('page_path', models.CharField(max_length=300)),
                ('page_url', models.URLField(blank=True, max_length=1000)),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('referrer_url', models.URLField(blank=True, max_length=1000)),
                ('referrer_host', models.CharField(blank=True, max_length=200)),
                ('source_origin', models.CharField(blank=True, max_length=200)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['site_scope', 'occurred_at'], name='pageview_scope_time_idx'), models.Index(fields=['visitor_id', 'occurred_at'], name='pageview_visitor_time_idx'), models.Index(fields=['page_path', 'occurred_at'], name='pageview_path_time_idx')],
            },
        ),
    ]
